---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket with data expired and deleted in 1 day
Resources:
  OneDayExpirationS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub one-day-expiration-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Expire-after-1day
            Status: Enabled
            ExpirationInDays: 1
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: Name
          Value: !Sub one-day-expiration-${AWS::AccountId}
  OneDayExpirationS3BucketIamGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub one-day-expiration-bucket-user-group-${AWS::AccountId}
      Path: /
      Policies:
        - PolicyName: !Sub one-day-expiration-bucket-user-policy-${AWS::AccountId}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Describe*
                  - s3:Get*
                  - s3:List*
                  - s3:*Object*
                  - s3:*MultipartUpload*
                  - s3-object-lambda:Get*
                  - s3-object-lambda:List*
                  - s3-object-lambda:*Object*
                  - s3-object-lambda:*MultipartUpload*
                Resource:
                  - Fn::Join:
                      - ''
                      - - 'arn:aws:s3:::'
                        - !Ref OneDayExpirationS3Bucket
                  - Fn::Join:
                      - ''
                      - - 'arn:aws:s3:::'
                        - !Ref OneDayExpirationS3Bucket
                        - /*
Outputs:
  OneDayExpirationS3Bucket:
    Value: !Ref OneDayExpirationS3Bucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-OneDayExpirationS3Bucket
  OneDayExpirationS3BucketIamGroup:
    Value: !Ref OneDayExpirationS3BucketIamGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-OneDayExpirationS3BucketIamGroup
