---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket with data expired and deleted in 1 day
Resources:
  OneDayExpirationBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub one-day-expiration-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: OneDayExpiredDataRemoval
            Status: Enabled
            ExpirationInDays: 1
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
  OneDayExpirationBucketUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub one-day-expiration-bucket-user-group-${AWS::AccountId}
      Path: /
      Policies:
        - PolicyName: !Sub one-day-expiration-bucket-user-policy-${AWS::AccountId}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Describe*
                  - s3:Get*
                  - s3:List*
                  - s3:*Object*
                  - s3:*MultipartUpload*
                  - s3-object-lambda:Get*
                  - s3-object-lambda:List*
                  - s3-object-lambda:*Object*
                  - s3-object-lambda:*MultipartUpload*
                Resource:
                  - Fn::Join:
                      - ''
                      - - 'arn:aws:s3:::'
                        - !Ref OneDayExpirationBucket
                  - Fn::Join:
                      - ''
                      - - 'arn:aws:s3:::'
                        - !Ref OneDayExpirationBucket
                        - /*
Outputs:
  OneDayExpirationBucket:
    Value: !Ref OneDayExpirationBucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-OneDayExpirationBucket
  OneDayExpirationBucketUserGroup:
    Value: !Ref OneDayExpirationBucketUserGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-OneDayExpirationBucketUserGroup
